# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
# Copyright 2024 Kyunghee University
# Copyright 2025 The Linux Foundation
name: Publish image and tag/release code

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    uses: onosproject/.github/.github/workflows/tag-github.yml@main
    if: (github.repository_owner == 'onosproject')
    secrets: inherit

  bump-up-version:
    needs: tag-and-release
    if: needs.tag-and-release.outputs.changed == 'true'
    uses: onosproject/.github/.github/workflows/bump-version.yml@main
    secrets: inherit
    with:
      version: ${{ needs.tag-and-release.outputs.version }}
